version: 2.1

executors:
  lein:
    docker:
      - image: circleci/clojure:openjdk-8-lein
    environment:
      LEIN_ROOT: true
      JVM_OPTS: -Xmx3200m

commands:
  caching_lein_deps:
    description: >
      Restore cached dependencies for this version of project.clj (if any),
      then run lein deps and cache the result.
    steps:
      - restore_cache:
          key: lein-deps-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
            - ~/.lein
          key: lein-deps-{{ checksum "project.clj" }}

jobs:
  test:
    executor: lein
    steps:
      - checkout
      - caching_lein_deps
      - run: lein do fetch --no-db --no-card-images, eftest

  install_js_deps:
    docker:
      - image: node
    steps:
      - checkout
      - run: npm install -g bower
      - run: bower --allow-root install
      - persist_to_workspace:
          root: .
          paths:
            - resources/public/lib

  build_css:
    docker:
      - image: node
    steps:
      - checkout
      - run: npm install -g stylus
      - run: stylus src/css -o resources/public/css
      - persist_to_workspace:
          root: .
          paths:
            - resources/public/css

  build_cljs:
    executor: lein
    steps:
      - checkout
      - caching_lein_deps
      - run: lein cljsbuild once prod
      - persist_to_workspace:
          root: .
          paths:
            - resources/public/js/app10.js

  fetch_card_data:
    executor: lein
    steps:
      - checkout
      - caching_lein_deps
      - run: lein fetch --no-db
      - persist_to_workspace:
          root: .
          paths:
            - data
            - resources/public/img/cards

  build_uberjar:
    executor: lein
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: ls -la resources/public/css/
      - run: ls -la resources/public/img/cards/
      - caching_lein_deps
      - run: lein uberjar
      - store_artifacts:
          path: target/netrunner-standalone.jar
      - persist_to_workspace:
          root: .
          paths:
            - target/netrunner-standalone.jar

  # upload_artifact:
  #   docker:
  #     - image: circleci/golang:1.8
  #   steps:
  #     - attach_workspace:
  #         at: .

workflows:
  version: 2
  test_and_build:
    jobs:

      - test

      - install_js_deps:
          # filters:
          #   branches:
          #     only: master
          requires: [test]

      - build_css:
          # filters:
          #   branches:
          #     only: master
          requires: [test]

      - build_cljs:
          # filters:
          #   branches:
          #     only: master
          requires: [test]

      - fetch_card_data:
          # filters:
          #   branches:
          #     only: master
          requires: [test]

      - build_uberjar:
          # filters:
          #   branches:
          #     only: master
          requires:
            - install_js_deps
            - build_css
            - build_cljs
            - fetch_card_data
